### PR TITLE
fix: fixed initial loading error and added scaffolding for tabbing error

### LINKED ISSUE #11: Pressing the Tab key inside the text box should not change the focus
If the Tab key is pressed and the focus is on the text box a Tab character should be printed to the Textbox.
At this moment the focus changes.

### LINKED ISSUE #34: CSS styles dont render markdown file at startup
Something was changed in index.js so the markdown file is not rendered when loading the page

### PR DESCRIPTION
**Pull request by Szlemens00**
Its not working yet - it should but unfortunately it isnt.

### CODE REVIEW

File: site/index.js [hunk 1]
```diff
@@ -1,7 +1,10 @@
 var js = import("../pkg/md_collab.js");
 
+window.addEventListener("load", render_html);
```
Comment (NelDav) [inline site/index.js:3]: I like this solution. It is much nicer than the `render_html();` call at the end of the file.

**Review by NelDav — CHANGES_REQUESTED** [review]
There are a few errors in the code which fixes #11. I think it is easier if I commit to this branch than mark them here.

**Review by NelDav — APPROVED** [review]
